name: BewerbungsPlugin
main: de.benangelo.main.Main
version: 1.5
author: Luis Benedikt

commands:
   EC:
      description: Oeffnet deine Enderchest!
   value:
      description: Du kannst dir geld geben!
   pay:
      description: Du kannst einem anderen Spieler geld geben!
   bank:
      description: Du kanst dein Geld sicher einer eine Datenbank legen!