name: BewerbungsPlugin
main: de.benangelo.main.Main
version: 3.0
author: Luis Benedikt

commands:
   EC:
      description: Oeffnet deine Enderchest!
   value:
      description: Du kannst dir geld geben!
   pay:
      description: Du kannst einem anderen Spieler geld geben!
   bank:
      description: Du kanst dein Geld sicher einer eine Datenbank legen!
   ban:
      description: Bannt einen Spieler fuer immer!
   tempban:
      description: Bannt einen Spieler fuer die eigegebenen Sekunden!
   unban:
      description: Entbannt einen Spieler!
   check:
      description: Zeigt infos ueber gebanntes Spieler!
   crafting:
      description: oeffnet einen Craftingtable!
   gm:
      description: Aendert deinen Spielmodus!
   invsee:
      description: Oeffnet das Inventar eines anderen spielers!
   tpa:
      description: Du kannst einem mitspieler eine Teleportationsanfrage schicken!